version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: transaction_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: transaction
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "4001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    extra_hosts:
        host.docker.internal: host-gateway
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: